theme = "soho"
baseurl = "https://www.bwilden.com/"
languageCode = "en"
title = "Bertrand Wilden"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
googleAnalytics = "G-C02SNMB3TQ"
# relativeURLs = true

[params]
title = "Bertrand Wilden"
description = "[Site under construction]"
# gravatar = "soho@example.com"
images = ["images/profile.jpeg"]
profilePicture = "images/profile.jpeg"
copyright = "Bertrand Wilden"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSection = ["post"]


## Set custom theme color.
themeColor = "#103E4F"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/bertrand-wilden-84041a153/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/bwilden"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/bertrand_wilden"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 1
  url = "/about"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 2
  url = "/contact"

  [[menu.main]]
  name = "Blog"
  weight = 3
  identifier = "blog"
  url = "/blog"

  [[menu.main]]
  name = "Teaching"
  identifier = "teaching"
  weight = 4
  url = "/teaching"
  
  [[menu.main]]
  name = "Data"
  identifier = "data"
  weight = 5
  url = "/data"
  
##  [[menu.main]]
##  name = "Categories"
##  weight = 200
##  identifier = "categories"
##  url = "/categories/"

##  [[menu.main]]
##  name = "Tags"
##  weight = 200
##  identifier = "tags"
##  url = "/tags/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
